# Generated by Django 5.0.6 on 2025-10-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileIntegrity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
                ("filename", models.CharField(max_length=13)),
                ("hash_data", models.CharField(max_length=64)),
                ("last_checked", models.DateTimeField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
