# Generated by Django 5.2.8 on 2025-11-12 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finlogic", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileintegrity",
            name="latest_category_expense_data",
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name="fileintegrity",
            name="filename",
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
