# Generated by Django 5.2.8 on 2025-11-12 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finlogic", "0002_fileintegrity_latest_category_expense_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileintegrity",
            name="latest_category_expense_data",
            field=models.JSONField(default=dict),
        ),
    ]
