# Generated by Django 5.2.8 on 2025-11-14 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finlogic", "0003_alter_fileintegrity_latest_category_expense_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileintegrity",
            name="latest_monthly_expense_data",
            field=models.JSONField(default=dict),
        ),
    ]
